#!/usr/bin/env bash
# run-codex.sh — generated driver for the 'seo-article' agent graph.
# Generated by emit_drivers.py — regenerate after recompiling; do not hand-edit.
#
# Chains headless `codex exec` calls, one per node. Gates are jq
# branches on state JSON. Resumable: progress persists in
# state/_run.json; re-run the script to continue a parked run.
set -euo pipefail

GRAPH_DIR="$(cd "$(dirname "$0")/.." && pwd)"
STATE_DIR="$GRAPH_DIR/state"
RUN_FILE="$STATE_DIR/_run.json"
mkdir -p "$STATE_DIR" "$STATE_DIR/.last"
command -v codex >/dev/null || { echo "codex CLI not found" >&2; exit 1; }
command -v jq    >/dev/null || { echo "jq not found" >&2; exit 1; }

# ---- freshness + approval gate (mirrors compile_graph.py hashing) ----
content_hash() {
  local lines
  lines=$({ printf 'graph.md:%s\n' "$(shasum -a 256 "$GRAPH_DIR/graph.md" | cut -d" " -f1)"
    for f in "$GRAPH_DIR"/nodes/*.md; do
      [ -e "$f" ] || continue
      printf 'nodes/%s:%s\n' "$(basename "$f")" "$(shasum -a 256 "$f" | cut -d" " -f1)"
    done; } | LC_ALL=C sort)
  printf '%s' "$lines" | shasum -a 256 | cut -d" " -f1
}
LOCK="$GRAPH_DIR/graph.lock.json"
[ -f "$LOCK" ] || { echo "no graph.lock.json — compile first" >&2; exit 2; }
CUR_HASH=$(content_hash)
LOCK_HASH=$(jq -r '.hashes.content' "$LOCK")
APPROVED_HASH=$(jq -r '.approval.graph_hash // empty' "$LOCK")
if [ "$CUR_HASH" != "$LOCK_HASH" ]; then
  echo "STALE: graph files changed since compile — recompile, re-validate, re-approve" >&2; exit 2
fi
if [ "$CUR_HASH" != "$APPROVED_HASH" ]; then
  echo "UNAPPROVED: the map has not passed its validation gate" >&2; exit 2
fi

MAX_STEPS=14
ENTRY='audit'
current="$ENTRY"; step=0
if [ -f "$RUN_FILE" ]; then
  current=$(jq -r .current "$RUN_FILE"); step=$(jq -r .step "$RUN_FILE")
  echo "resuming at node $current (step $step)"
fi

save_run() { printf '{"current":"%s","step":%s}\n' "$1" "$2" > "$RUN_FILE"; }

run_audit() {
  echo "node audit [fable:frontier -> gpt-5.6-sol]"
  local out="$STATE_DIR/.last/audit.out"
  codex exec \
    -m 'gpt-5.6-sol' \
    --sandbox workspace-write \
    --skip-git-repo-check \
    -o "$out" \
    --cd "$GRAPH_DIR" \
    "You are node 'audit' of the seo-article agent graph. Follow the brief at $GRAPH_DIR/nodes/01-audit.md exactly. State inputs — none. Your final message must be only the 'audit' output the brief's Writes section specifies. Do not do any other node's work." < /dev/null
  jq -e . "$out" >/dev/null || { echo "node audit: output is not valid JSON" >&2; exit 1; }
  cp "$out" "$GRAPH_DIR/state/audit.json"
}

run_draft_new() {
  echo "node draft-new [fable:frontier -> gpt-5.6-sol]"
  local out="$STATE_DIR/.last/draft-new.out"
  codex exec \
    -m 'gpt-5.6-sol' \
    --sandbox workspace-write \
    --skip-git-repo-check \
    -o "$out" \
    --cd "$GRAPH_DIR" \
    "You are node 'draft-new' of the seo-article agent graph (internal cap 3 — the brief carries its own bar). Follow the brief at $GRAPH_DIR/nodes/02-draft-new.md exactly. State inputs — audit: $GRAPH_DIR/state/audit.json. Your final message must be only the 'draft' output the brief's Writes section specifies. Do not do any other node's work." < /dev/null
  cp "$out" "$GRAPH_DIR/state/draft.md"
}

run_edit_ranking() {
  echo "node edit-ranking [fable:frontier -> gpt-5.6-sol]"
  local out="$STATE_DIR/.last/edit-ranking.out"
  codex exec \
    -m 'gpt-5.6-sol' \
    --sandbox workspace-write \
    --skip-git-repo-check \
    -o "$out" \
    --cd "$GRAPH_DIR" \
    "You are node 'edit-ranking' of the seo-article agent graph (internal cap 3 — the brief carries its own bar). Follow the brief at $GRAPH_DIR/nodes/03-edit-ranking.md exactly. State inputs — audit: $GRAPH_DIR/state/audit.json. Your final message must be only the 'draft' output the brief's Writes section specifies. Do not do any other node's work." < /dev/null
  cp "$out" "$GRAPH_DIR/state/draft.md"
}

run_assemble() {
  echo "node assemble [codex:balanced -> gpt-5.6-terra]"
  local out="$STATE_DIR/.last/assemble.out"
  codex exec \
    -m 'gpt-5.6-terra' \
    --sandbox workspace-write \
    --skip-git-repo-check \
    -o "$out" \
    --cd "$GRAPH_DIR" \
    "You are node 'assemble' of the seo-article agent graph. Follow the brief at $GRAPH_DIR/nodes/04-assemble.md exactly. State inputs — draft: $GRAPH_DIR/state/draft.md. Your final message must be only the 'article' output the brief's Writes section specifies. Do not do any other node's work." < /dev/null
  cp "$out" "$GRAPH_DIR/state/article.md"
}

run_score() {
  echo "node score [fable:balanced -> gpt-5.6-terra]"
  local out="$STATE_DIR/.last/score.out"
  codex exec \
    -m 'gpt-5.6-terra' \
    --sandbox read-only \
    --skip-git-repo-check \
    -o "$out" \
    --output-schema "$GRAPH_DIR/drivers/schemas/score.json" \
    --cd "$GRAPH_DIR" \
    "You are node 'score' of the seo-article agent graph. Follow the brief at $GRAPH_DIR/nodes/05-score.md exactly. State inputs — article: $GRAPH_DIR/state/article.md. Your final message must be only the 'review' output the brief's Writes section specifies. Do not do any other node's work." < /dev/null
  jq -e . "$out" >/dev/null || { echo "node score: output is not valid JSON" >&2; exit 1; }
  cp "$out" "$GRAPH_DIR/state/review.json"
}

run_fix() {
  echo "node fix [codex:frontier -> gpt-5.6-sol]"
  local out="$STATE_DIR/.last/fix.out"
  codex exec \
    -m 'gpt-5.6-sol' \
    --sandbox workspace-write \
    --skip-git-repo-check \
    -o "$out" \
    --cd "$GRAPH_DIR" \
    "You are node 'fix' of the seo-article agent graph. Follow the brief at $GRAPH_DIR/nodes/06-fix.md exactly. State inputs — review: $GRAPH_DIR/state/review.json; onpage: $GRAPH_DIR/state/onpage.json. Your final message must be only the 'draft' output the brief's Writes section specifies. Do not do any other node's work." < /dev/null
  cp "$out" "$GRAPH_DIR/state/draft.md"
}

run_add_links() {
  echo "node add-links [codex:fast -> gpt-5.6-luna]"
  local out="$STATE_DIR/.last/add-links.out"
  codex exec \
    -m 'gpt-5.6-luna' \
    --sandbox workspace-write \
    --skip-git-repo-check \
    -o "$out" \
    --cd "$GRAPH_DIR" \
    "You are node 'add-links' of the seo-article agent graph. Follow the brief at $GRAPH_DIR/nodes/07-add-links.md exactly. State inputs — article: $GRAPH_DIR/state/article.md; review: $GRAPH_DIR/state/review.json. Your final message must be only the 'final_article' output the brief's Writes section specifies. Do not do any other node's work." < /dev/null
  cp "$out" "$GRAPH_DIR/state/final_article.md"
}

run_onpage_audit() {
  echo "node onpage-audit [fable:balanced -> gpt-5.6-terra]"
  local out="$STATE_DIR/.last/onpage-audit.out"
  codex exec \
    -m 'gpt-5.6-terra' \
    --sandbox read-only \
    --skip-git-repo-check \
    -o "$out" \
    --output-schema "$GRAPH_DIR/drivers/schemas/onpage-audit.json" \
    --cd "$GRAPH_DIR" \
    "You are node 'onpage-audit' of the seo-article agent graph. Follow the brief at $GRAPH_DIR/nodes/08-onpage-audit.md exactly. State inputs — final_article: $GRAPH_DIR/state/final_article.md. Your final message must be only the 'onpage' output the brief's Writes section specifies. Do not do any other node's work." < /dev/null
  jq -e . "$out" >/dev/null || { echo "node onpage-audit: output is not valid JSON" >&2; exit 1; }
  cp "$out" "$GRAPH_DIR/state/onpage.json"
}

run_publish() {
  echo "node publish [codex:frontier -> gpt-5.6-sol]"
  local out="$STATE_DIR/.last/publish.out"
  codex exec \
    -m 'gpt-5.6-sol' \
    --sandbox workspace-write \
    --skip-git-repo-check \
    -o "$out" \
    --cd "$GRAPH_DIR" \
    "You are node 'publish' of the seo-article agent graph. Follow the brief at $GRAPH_DIR/nodes/09-publish.md exactly. State inputs — final_article: $GRAPH_DIR/state/final_article.md. Your final message must be only the 'published_url' output the brief's Writes section specifies. Do not do any other node's work." < /dev/null
  jq -e . "$out" >/dev/null || { echo "node publish: output is not valid JSON" >&2; exit 1; }
  cp "$out" "$GRAPH_DIR/state/published_url.json"
}

echo "run: $ENTRY -> __end__ (max_steps $MAX_STEPS)"
while :; do
  save_run "$current" "$step"
  case "$current" in
    __end__)
      rm -f "$RUN_FILE"
      echo "DONE — state/ holds the audit trail"; exit 0 ;;
    'page-ranks')
      if jq -e '.ranking_url != null' "$GRAPH_DIR/state/audit.json" >/dev/null 2>&1; then
        current='edit-ranking'
      else
        current='draft-new'
      fi ;;
    'rubric')
      if jq -e '.approved == true' "$GRAPH_DIR/state/review.json" >/dev/null 2>&1; then
        current='add-links'
      else
        current='fix'
      fi ;;
    'onpage')
      if jq -e '.approved == true' "$GRAPH_DIR/state/onpage.json" >/dev/null 2>&1; then
        current='publish'
      else
        current='fix'
      fi ;;
    'audit')
      step=$((step + 1))
      if [ "$step" -gt "$MAX_STEPS" ]; then
        echo "HALT: max_steps reached — last verdicts:" >&2
        ls "$STATE_DIR"/*.json >/dev/null 2>&1 && grep -l '"issues"' "$STATE_DIR"/*.json 2>/dev/null | while read -r f; do echo "--- $f"; jq -r '.issues[]?' "$f"; done >&2
        exit 1
      fi
      run_audit
      current='page-ranks' ;;
    'draft-new')
      step=$((step + 1))
      if [ "$step" -gt "$MAX_STEPS" ]; then
        echo "HALT: max_steps reached — last verdicts:" >&2
        ls "$STATE_DIR"/*.json >/dev/null 2>&1 && grep -l '"issues"' "$STATE_DIR"/*.json 2>/dev/null | while read -r f; do echo "--- $f"; jq -r '.issues[]?' "$f"; done >&2
        exit 1
      fi
      run_draft_new
      current='assemble' ;;
    'edit-ranking')
      step=$((step + 1))
      if [ "$step" -gt "$MAX_STEPS" ]; then
        echo "HALT: max_steps reached — last verdicts:" >&2
        ls "$STATE_DIR"/*.json >/dev/null 2>&1 && grep -l '"issues"' "$STATE_DIR"/*.json 2>/dev/null | while read -r f; do echo "--- $f"; jq -r '.issues[]?' "$f"; done >&2
        exit 1
      fi
      run_edit_ranking
      current='assemble' ;;
    'assemble')
      step=$((step + 1))
      if [ "$step" -gt "$MAX_STEPS" ]; then
        echo "HALT: max_steps reached — last verdicts:" >&2
        ls "$STATE_DIR"/*.json >/dev/null 2>&1 && grep -l '"issues"' "$STATE_DIR"/*.json 2>/dev/null | while read -r f; do echo "--- $f"; jq -r '.issues[]?' "$f"; done >&2
        exit 1
      fi
      run_assemble
      current='score' ;;
    'score')
      step=$((step + 1))
      if [ "$step" -gt "$MAX_STEPS" ]; then
        echo "HALT: max_steps reached — last verdicts:" >&2
        ls "$STATE_DIR"/*.json >/dev/null 2>&1 && grep -l '"issues"' "$STATE_DIR"/*.json 2>/dev/null | while read -r f; do echo "--- $f"; jq -r '.issues[]?' "$f"; done >&2
        exit 1
      fi
      run_score
      current='rubric' ;;
    'fix')
      step=$((step + 1))
      if [ "$step" -gt "$MAX_STEPS" ]; then
        echo "HALT: max_steps reached — last verdicts:" >&2
        ls "$STATE_DIR"/*.json >/dev/null 2>&1 && grep -l '"issues"' "$STATE_DIR"/*.json 2>/dev/null | while read -r f; do echo "--- $f"; jq -r '.issues[]?' "$f"; done >&2
        exit 1
      fi
      run_fix
      current='assemble' ;;
    'add-links')
      step=$((step + 1))
      if [ "$step" -gt "$MAX_STEPS" ]; then
        echo "HALT: max_steps reached — last verdicts:" >&2
        ls "$STATE_DIR"/*.json >/dev/null 2>&1 && grep -l '"issues"' "$STATE_DIR"/*.json 2>/dev/null | while read -r f; do echo "--- $f"; jq -r '.issues[]?' "$f"; done >&2
        exit 1
      fi
      run_add_links
      current='onpage-audit' ;;
    'onpage-audit')
      step=$((step + 1))
      if [ "$step" -gt "$MAX_STEPS" ]; then
        echo "HALT: max_steps reached — last verdicts:" >&2
        ls "$STATE_DIR"/*.json >/dev/null 2>&1 && grep -l '"issues"' "$STATE_DIR"/*.json 2>/dev/null | while read -r f; do echo "--- $f"; jq -r '.issues[]?' "$f"; done >&2
        exit 1
      fi
      run_onpage_audit
      current='onpage' ;;
    'publish')
      step=$((step + 1))
      if [ "$step" -gt "$MAX_STEPS" ]; then
        echo "HALT: max_steps reached — last verdicts:" >&2
        ls "$STATE_DIR"/*.json >/dev/null 2>&1 && grep -l '"issues"' "$STATE_DIR"/*.json 2>/dev/null | while read -r f; do echo "--- $f"; jq -r '.issues[]?' "$f"; done >&2
        exit 1
      fi
      run_publish
      current='__end__' ;;
    *) echo "unknown state: $current" >&2; exit 1 ;;
  esac
done
